version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/processflow
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  go_parser:
    build: ./go_parser
    ports:
      - "8081:8081"