---
- name: Sample Automation Playbook
  hosts: localhost
  tasks:
    - name: Install package
      apt:
        name: nginx
        state: present
    - name: Start service
      service:
        name: nginx
        state: started